[package]
name = "rpi-hello"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
peripheral_linux = { path = "../peripheral-linux/" }
peripheral = { path = "../peripheral/"}
spidev = "0.3"
